version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports: 
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    networks:
      vpcbr:
        ipv4_address: 10.5.11.111
    environment:
      WEBPASSWORD: 'dnsoverhttps'
      DNS1: '10.5.11.53#5053'
      DNS2: '10.5.11.53#5053'
    restart: unless-stopped
  cloudflared:
    container_name: cloudflared
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5053:5053/udp"
      - "49312:49312/tcp"
    networks:
      vpcbr:
        ipv4_address: 10.5.11.53
    restart: unless-stopped

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.11.0/24
